- build.gradle.kts
- settings.gradle.kts
- web1-api/src/main/kotlin/com/yapp/web1be/test/TestService.kt
- web1-api/src/test/kotlin/com/yapp/web1be/test/TestServiceTest.kt
- web1-domain/build.gradle.kts
- web1-domain/src/main/kotlin/com/yapp/web1be/test/TestEntity.kt
- web1-infra/build.gradle.kts
- close #8 
- kotest, mockk 추가
- @cofls6581  build.gradle.kts 설정 다른분들 repo 참고해서 가독성이 좀 더 좋은것 같아 변경해보았는데 괜찮으실까요..?
- 인텔리제이에서 kotest 실행시 plugin 설치 필요 - [kotest](https://plugins.jetbrains.com/plugin/14080-kotest)
- [kotest 테스트 스타일 참고](https://kotest.io/docs/framework/testing-styles.html)
- kotest-framework-datatest 의존성은 [Data Drive Testing](https://kotest.io/docs/framework/datatesting/data-driven-testing.html) 위해 추가
- [mockk](https://mockk.io/)은 코를린 mock 라이브러리
- ninja-squad:springmockk은 spring에서 mockk 사용을 위한 라이브러리
> Feat/8 kotest mockk 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/Application.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/test/TestResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/test/TestService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/test/TestServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/BaseTimeEntity.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/test/entity/TestEntity.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/test/repository/TestQuerydslRepository.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/test/repository/TestRepository.kt
- close #20 
- 도메인 패키징 구조 잡기 (test 예시 참조)
- BaseTimeEntity 생성
erd 설계 기준으로 컬럼명 맞췄습니다.
디폴트로 null 대신 현재 시각 사용했습니다.
[JPA Auditing with kotlin](https://velog.io/@tkppp-dev/Spring-Data-JPA-Auditing-with-Kotlin)
> feat : BaseTimeEntity 생성

- .github/workflows/cicd.yml
- .gitignore
- docker-compose.yml
- muckpot-api/Dockerfile
- muckpot-domain/src/main/resources/application-dev.yml
- close #23 
서브모듈 방식을 활용한 민감정보 관리는 보안상 취약한 단점이 있어 시스템 환경 변수를 사용하는 방식으로 작업했습니다.
- .env 설정 후 기존 민감정보 값 매핑
- .env .gitignore에 추가
- dev 환경 cicd 스크립트에 .env 동기화 로직 추가
- github secrets에 ENV_VARS(.env 값) 추가
- keybase에 .env 파일 업로드 완료
+ 추가 작업
- 기존 cicd 스크립트를 dev환경 cicd 스크립트로 더 구체적으로 명시하여 수정했습니다.
- docker run 명령어에 --restart=unless-stopped 추가했습니다. (컨테이너 비정상 종료 시 자동 재시작 옵션) 
- .env 인텔리제이에서 설정법
run→edit configurations→enable env file→shift+command+.(파인더 숨긴 파일 보기 명령어)→env파일 추가→apply
- .env 파일 변경이 생길 시
keybase와 github ENV_VARS 최신화 후 변경 사항 생겼다고 pr에 언급 부탁드립니다!
ec2 내 .env는 cicd 스크립트에서 자동으로 덮어씌워지도록 로직 추가해둬서 따로 신경 안쓰셔도됩니당ㅎㅎ
> feat: .env 설정

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/JwtConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/config/SecurityConfig.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtAuthorizationFilter.kt
- close #35
- 비회원 접근 가능 URL 추가
- 회원가입, 이메일 인증, 이메일 전송
> fix: 35-비로그인 유저 가능 api 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/SwaggerConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/dto/CursorPaginationRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/dto/CursorPaginationResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotReadResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/exception/GlobalExceptionHandler.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/common/TimeUtilTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/fixture/Fixture.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/TimeConstant.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/TimeUtil.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/extension/LocalDate.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/dto/ParticipantReadResponse.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/BoardQuerydslRepository.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/ParticipantQuerydslRepository.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/user/enums/MuckPotStatus.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/repository/BoardQuerydslRepositoryTest.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/repository/ParticipantQuerydslRepositoryTest.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/repository/ParticipantRepositoryTest.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/user/repository/MuckPotUserRepositoryTest.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/fixture/Fixture.kt
- close #43
- 먹팟 조회 api 구현
- [ref](https://velog.io/@minsangk/%EC%BB%A4%EC%84%9C-%EA%B8%B0%EB%B0%98-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98-Cursor-based-Pagination-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0)
- 게시글: 최신순
- 참가자: 신청 선착순
- 프로필은 최대 5명, 초과 시 외N 명 **(외N명은 클릭 불 가능)**
- 모집 중, 모집 마감
- 시간 정책
- 60분 미만 => n분 전
- 1시간 이상 ~ 24시간 미만 => n시간 전
- 24시간 이상 ~ 48시간 미만 => 하루 전
- 나머지 => YYYY년 MM월 DD일 (요일) 오전/오후 HH:MM, 썸네일에서는 YY.MM.DD
> feat:43 먹팟 조회 api 구현

- muckpot-api/src/main/kotlin/com/yapp/muckpot/config/SecurityConfig.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtAuthorizationFilter.kt
- close #51
- cors 설정 변경
- 우선, 기존설정만 변경해보았습니다. 배포 후 안되면 FE 환경 구축하여 다시 테스트 해보겠숩니다..
- allowedOrigins -> allowedOriginPatterns 변경
- allowedOrigins에 * 값을 포함하는 경우 allowCredentials가 true로 설정되어 있더라도 CORS 정책을 준수할 수 없다고 함.
- 로그인한 유저가 다시 로그인, 회원가입하지못하는 로직 조건 같이 수정하였습니다 !
> bug: 51 cors 설정 변경 및 로그인 유저 회원가입 및 로그인 요청 조건 수정

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/SecurityContextHolderUtil.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/SwaggerConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/config/SecurityConfig.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotReadResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/UserController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/JwtService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/UserService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtAuthorizationFilter.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/common/TimeUtilTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponseTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/Location.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/RegexPatternConst.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/TimeConstant.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/TimeUtil.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/dto/ParticipantReadResponse.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/exception/BoardErrorCode.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/ParticipantQuerydslRepository.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/user/enums/MuckPotStatus.kt
- close #50 
- 먹팟 상세조회 구현
- 로그인 유저가 참여한 먹팟이라면 가장 상단에 위치한다.
- 조직장인 경우: writer: true
- 아닌 경우: 필드 없음.
- 상세 조회시 조회수 증가
- 먹팟 글 리스트 조회랑 같은 응답 Dto 사용하려고 공통처리해서, 기존 먹팟 글 리스트 조회시 참여자 목록에 jobGroupMain 추가되었습니다.
- 프로필 조회 api 에서 Cookie를 다시 읽을 필요가 없을것 같아서 SecurityContextHolder에서 유저정보 가져오도록 변경하였습니다.
-`/users/profile`
- 시간 관련 상수 위치 변경하였습니다.
- enum 한글 명 korNm 으로 통일하였습니다.
> feat: 50 먹팟 상세조회 구현

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/entity/BoardTest.kt
- close #62 
- 먹팟 글 상태변경 API 구현
- 모집 종료는 IN_PROGRESS 상태에서만 가능
- 다시 모집은 DONE 상태이면서, currentApply < maxApply 상태에서만 가능
> feat: 먹팟 글 상태변경 API 구현

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/JwtConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/JwtCookieUtil.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/ValidationMessageConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotUpdateRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/JwtService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/UserService.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/constants/TimeConstant.kt
- muckpot-infra/src/main/kotlin/com/yapp/muckpot/redis/RedisService.kt
- close #65
- 기존 만료시간이 없는 토큰의 경우 보안상 취약하여, 로그인 유지하기 기능에도 만료시간을 지정하였습니다.
- as-is
- 로그인 유지하기 선택: 토큰 만료기한 없음
- 로그인 유지하기 미선택: 한시간, 일주일
- to-be
- 로그인 유지하기 선택: Access 1일, Refresh 30일
- [카카오 로그인 API 참조하여 30일](https://cs.kakao.com/helps?articleId=1073192624&service=52&category=166&device=423&locale=ko)
- 로그인 유지하기 미선택: 한시간, 일주일
> refactor: 65 로그인 유지하기 만료시간 지정

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/exception/ParticipantErrorCode.kt
- close #67 
- 먹팟 참가 신청 취소 api 구현
participant table soft delete
muckpot_user.current_apply update
- validation 처리
- 테스트 코드 작성
- ParticipantErrorCode enum 생성
> feat : 67 먹팟 참가 신청 취소 api 구현

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- close #78 
- 먹팟 글 상제 조회 API 응답 추가 요청 작업
- userAge 값 추가
- 로그인 유저 = 나이 값 계산 후 반환
- 비로그인 유저=  null 반환
- 내용을 적어주세요.
> feat:  78 먹팟 글 상제 조회 API 응답 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/utils/CookieUtil.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/config/TomcatConfig.kt
- close #87 
- 쿠키 발급시 도메인 지정.
- 로컬호스트에서 접근 할 수 있도록 허용
- 도메인이 제대로 발급되는지는 테스트를 못했습니다..
- 로컬에서 `.localhost` 발급 테스트 진행했는데 `An invalid domain ... was specified for this cookie`  예외가 발생해서 TomcatConfig를 추가했습니다.
- [Ref](https://danawalab.github.io/common/2020/02/11/Common-Tomcat-cookieProcessor.html)
- 설정 추가하니 쿠키 발급은 되는데.. 도메인에 `.localhost` 가 아닌, `localhost`로 발급되었습니다..
- 원인은 못찾았습니다..
- 우선 배포 후, 확인을 해봐야할 것 같아요..!
> refactor: cookie 발급시 도메인 지정

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/utils/CookieUtil.kt
- close #87 
- Host 헤더로는 localhost를 구분할 수 없음.
- Origin 으로 로컬요청 확인 후, `domain: localhost` 쿠키 발급
- 해당 로직은 v1.0 배포이전 분리해야할 것 같습니다..!
> fix: 87 로컬 접근 시 쿠키 발급 로직 변경

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/ParticipantService.kt
- muckpot-infra/src/main/kotlin/com/yapp/muckpot/email/EmailTemplate.kt
- close #100 
- 먹팟 글 삭제시 메일 전송
- 자신에게는 메일을 보내지 않음.
- 메일 조회 및 이메일 전송 기능이 중복사용되어 ParticipantService로 분리하였습니다.
> feat: 100 먹팟 글 삭제시 메일 전송

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/ParticipantService.kt
- muckpot-infra/src/main/kotlin/com/yapp/muckpot/email/EmailTemplate.kt
- close #104 
- 먹팟 참여 취소시 참가인원 모두에게 메일 전송
- 취소자 본인에게는 메일을 보내지 않는다.
- @cofls6581 100번 이슈 merge 후 슬랙멘션 남겨놓겠습니다. (현재 Draft)
> feat: 104 먹팟 참여취소시 메일 전송

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotReadResponse.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- 오늘, 내일 데이터가 createAt 기준으로 생성되고 있어, meetingTime으로 변경하였습니다.
- [QA 노션 링크
](https://www.notion.so/yapp-workspace/2ac19bc223034e919f062dec168d68f6?pvs=4)
- close #108 
- 오늘 내일 데이터 기준 변경
- createdAt이 아닌 meetingTime 기준으로 생성되도록 변경
- 오늘(7월 8일)이고, 먹팟 날짜가 9월 27일 인데.. 오늘이 표시되고 있음.
> fix: 108 오늘내일 데이터 오류 개선

- muckpot-api/Dockerfile
- close #108 
- LocalDateTime이 9시간 차이나서 타임존 지정
- LocalDate.now() 로 비교할 때 현재시간과 9시간이 차이나고 있어서 문제가 되고 있습니다.
- ex) 7월 9일 먹팟이 내일로 보여지고 있음.
- Dockerfile에 타임존 지정하였습니다.
> fix: 108 timeZone 9시간 차이나서 수정

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/ProvinceService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/LoginRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/SignUpRequestV1.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequestTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/City.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Province.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/CityRepository.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/ProvinceRepository.kt
- close #102 
- 먹팟 글 생성 api v2 개발
- 먹팟 생성 시 새로운 지역의 경우 최초 1회만 city, province 테이블에 값 저장
- 먹팟 글 생성 관련 테스트 코드 작성 및 수정
스웨거 회원가입, 로그인 예시 요청 값 통일하여 예시 요청 값 그대로 api 사용 가능하게 변경했습니다.
> feat: 102 먹팟 글 생성 api v2 개발

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/constants/UrlConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/config/SecurityConfig.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/UserController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/UserDeprecatedController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/LoginRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/SendEmailAuthRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/SignUpRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/VerifyEmailAuthRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/deprecated/LoginRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/deprecated/SendEmailAuthRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/deprecated/SignUpRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/controller/dto/deprecated/VerifyEmailAuthRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/UserDeprecatedService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtAuthorizationFilter.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/constants/BoardConstant.kt
- close #111
- 로그인, 이메일 인증 요청, 이메일 인증 검증 API 유효성 검사 변경
- as-is: naver.com
- to-be: samsung.com
- Deprecated 대상이 너무 많아져서.. 클래스를 분리했습니다.
> feat:111 로그인, 이메일 인증 요청, 검증 API 이메일 삼성으로 변경

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/RegionFilterRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/BoardQuerydslRepository.kt
- close #116 
- 먹팟 상세 조회시 지역정보(cityId, provinceId)를 쿼리파라미터 추가
- provinceId는 있지만, cityId가 없는 경우는 예외처리 하였습니다.
> feat: 상세 조회 지역정보 쿼리파라미터 추가

- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/entity/BoardTest.kt
- close #120 
- 참여 취소시 상태 변경
- [노션 링크](https://www.notion.so/yapp-workspace/1d0d68f0896e4399b63cc509a6f7443c?pvs=4)
- 먹팟 참여 취소 시 상태 변경 추가
- 먹팟 시간이 지난 경우에는 취소하지 못하게 유효성 검사 추가하였습니다.
- 참여 취소 시 항상 IN_PROGRESS로 변경하도록 변경하였습니다.
> fix: 120 참여 취소시 상태변경

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/constants/SwaggerConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/BoardController.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotUpdateDetailResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/common/TimeUtilTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/common/constants/RegexPatternConst.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/ParticipantQuerydslRepository.kt
- close #131
- 먹팟 수정시 상세 조회 API를 사용하게되면 조회수가 증가되기 때문에 별도 조회 API 추가
- 먹팟 상세 조회시 YYYY 년도 누락되어 추가
> refactor: 131 먹팟 상세 년도 추가, 수정 조회 API 추가

- .github/workflows/ci.yml
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardScheduler.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/exception/BoardErrorCode.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/entity/BoardTest.kt
- close #137 
- 먹팟 수정
-  만료된 먹팟은 수정 불가능.
- 먹팟 상태 변경
- 유효성 검사 추가
- 현재시간 이전 먹팟 상태변경 불가능 유효성 추가
- 기존 유효성 검사로직 삭제
- 모집 인원이 마감된 경우에도 변경 가능하도록 기존 유효성 검사로직 삭제
- 수정을 위해서 변경가능하도록 허용
- 캐시삭제 추가
- 스케줄러에서 먹팟 상태가 변경되기 때문에 캐시 삭제
> refactor:137 먹팟 수정, 참여상태 변경 유효성검사 추가, 스케줄러 캐시 삭제 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/ProvinceService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/user/enums/MuckPotStatus.kt
- muckpot-domain/src/testFixtures/kotlin/Fixture.kt
- close #139 
- 먹팟 참여, 취소 시 상태가 변경되는 경우가 존재.
- 이 경우 카테고리 상태가 변경되기 때문에 캐시 삭제로직 추가
- Fixture 코드 수정
- 제약조건에 맞추어 수정 -> user.nickname은 10자까지만 저장 가능
- DONE 한글명 변경
- 1.0 피그마에 맞추어 모집마감 -> 모집 종료로 변경하였습니다.
> bug: 139 캐시 삭제로직 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/ProvinceService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/ProvinceRepository.kt
- close #148 
-  중복 이름의 province가 저장되기 때문에 findByName의 결과를 List로 받을 수 있도록 변경하였습니다.
> fix: 148 provinceName으로 조회시 list가 될 수 있어서 대응

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/constants/ValidationMessageConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponse.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotUpdateRequest.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/deprecated/MuckpotCreateRequestV1.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/controller/dto/deprecated/MuckpotUpdateRequestV1.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequestTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotDetailResponseTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/entity/Board.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/entity/BoardTest.kt
- close #152 
- 먹팟 생성
- 현재시간 미만의 먹팟은 모집 종료 상태로 생성
- 먹팟 수정
- 현재시간 미만의 먹팟은 모집 종료 상태로 변경
- 변경된 내용이 없을 때 수정할 수 없도록 유효성 추가
- 생성 & 수정
- 최대참여인원 2 ~ 100 제한
- 먹팟 상세
- 날짜 지난 경우 모집 마감 버튼 비활성화를 위해 isOutOfDate 필드 추가
> feat: 152 먹팟 생성, 수정, 상세 QA

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/utils/CookieUtil.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/user/service/JwtService.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtAuthorizationFilter.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/filter/JwtLogoutHandler.kt
- close #159 
- 로그아웃 -> accessToken 블랙리스트 등록 -> 블랙리스트 ttl 만료 -> 쿠키가 남아있음 -> 회원가입 과정에서 토큰 만료를 검사하고 있음
- 로그아웃시 쿠키삭제하도록 로직추가
- 비로그인 유저만 사용가능한 API 추가
- 이메일 인증 요청, 이메일 인증 API는 로그인 유저는 접근할 수 없음. filter에 추가 함.
> bug: 159 로그아웃 쿠키삭제, 비로그인만 접속가능한 API 추가

- muckpot-api/src/main/kotlin/com/yapp/muckpot/common/constants/ValidationMessageConstant.kt
- muckpot-api/src/main/kotlin/com/yapp/muckpot/domains/board/service/BoardService.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/controller/dto/MuckpotCreateRequestTest.kt
- muckpot-api/src/test/kotlin/com/yapp/muckpot/domains/board/service/BoardServiceMockTest.kt
- muckpot-domain/src/main/kotlin/com/yapp/muckpot/domains/board/repository/BoardQuerydslRepository.kt
- muckpot-domain/src/test/kotlin/com/yapp/muckpot/domains/board/repository/BoardQuerydslRepositoryTest.kt
- close #161 
- 조회 정렬순서 변경
- 먹팟 전체조회 정렬기준 변경
- 모집중 -> 모집마감 순서로 조회
- 먹팟 상세 이전, 이후 아이디 조회로직도 정렬조건 동일하게 맞춤
- 기존 prevId, nextId 조회 쿼리 삭제 후, 정렬조건 맞춰서 이전, 이후 아이디를 한번에 찾는 findPrevAndNextId 쿼리 추가하였습니다. 
- 이부분.. lag나 lead를 써서 풀고싶었는데.. querydsl에서 못쓴다그래서.. 좀 무식하게 풀어놨습니다.. 혹시 더 나은 방안 제안주시면 고쳐볼게요 !
> refactor: 161 조회 정렬순서 변경
